import React, { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import albumArt from "album-art";

import Jimpod from "../public/jimpod.jpg";

export default function Home() {
  const [query, setQuery] = useState();
  const [searchQuery, setSearchQuery] = useState();
  const [album, setAlbum] = useState();

  useEffect(() => {
    if (searchQuery) albumArt("", { album: searchQuery }).then(setAlbum);
  }, [searchQuery]);

  const handleChange = (e) => {
    setQuery(e.target.value);
  };
  const handleSubmit = (e) => {
    e.preventDefault();
    setSearchQuery(query);
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="max-w-4xl mx-auto">
          <form onSubmit={handleSubmit}>
            <input onChange={handleChange} />
            <button>Search</button>
          </form>
          <div className="relative">
            {album && (
              <div
                className="absolute bottom-[34.5%] left-[11%] z-10"
                style={{
                  transform: `rotateX(33deg) rotateZ(-16deg) rotateY(4deg)`,
                }}
              >
                <Image src={album} alt="" height={76} width={76} />
              </div>
            )}
            <Image src={Jimpod} alt="Jim Halpert listening to an iPod." />
          </div>
        </div>
      </main>
    </div>
  );
}
